name: CI

on:
  - workflow_dispatch
  - pull_request

concurrency:
  group: ${{ github.ref_name }}-expressly
  cancel-in-progress: true

jobs:
  build:
    name: expressly
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.AUTO_GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Node modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-expressly-${{ secrets.cache_key_epoch_time }}-${{ hashFiles('yarn.lock') }}
      - name: Compile expressly
        run: yarn build
      - name: Test expressly
        run: yarn test
      - name: Publish
        run: |
          git fetch origin 'refs/tags/*:refs/tags/*'
          yarn auto shipit
